import { useEffect, useState, useCallback } from 'react';
import { supabase } from '../lib/supabase';
import { useActivityLog } from './useActivityLog';
import type { JobIssue } from '../types/production';

export function useJobIssues(jobId: string | undefined) {
  const [issues, setIssues] = useState<JobIssue[]>([]);
  const [photoUrls, setPhotoUrls] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const { append } = useActivityLog();

  const load = useCallback(async () => {
    if (!jobId) return;
    setLoading(true);
    const { data, error } = await supabase
      .from('job_issues')
      .select('*')
      .eq('job_id', jobId)
      .order('created_at', { ascending: false });
    if (error) {
      console.error('[useJobIssues] load failed:', error);
      setIssues([]);
      setPhotoUrls({});
      setLoading(false);
      return;
    }
    const rows = (data ?? []) as JobIssue[];
    setIssues(rows);

    const ids = Array.from(new Set(rows.flatMap((r) => r.photos ?? [])));
    if (ids.length === 0) {
      setPhotoUrls({});
      setLoading(false);
      return;
    }

    const { data: photos, error: pErr } = await supabase
      .from('job_photos')
      .select('photo_id, url')
      .in('photo_id', ids);
    if (pErr) {
      console.error('[useJobIssues] photo lookup failed:', pErr);
      setPhotoUrls({});
      setLoading(false);
      return;
    }

    // Stored urls were generated by getPublicUrl() at upload time, but the
    // bucket is private — those urls return 400 anonymously. Extract the
    // object path from each url and mint a fresh signed url for display.
    const rowsByPath: { photo_id: string; path: string }[] = [];
    for (const p of (photos ?? []) as { photo_id: string; url: string }[]) {
      const marker = '/job-photos/';
      const idx = p.url.indexOf(marker);
      if (idx === -1) continue;
      rowsByPath.push({ photo_id: p.photo_id, path: p.url.slice(idx + marker.length) });
    }
    const { data: signed, error: sErr } = await supabase
      .storage
      .from('job-photos')
      .createSignedUrls(rowsByPath.map((r) => r.path), 3600);
    if (sErr) {
      console.error('[useJobIssues] signed url mint failed:', sErr);
      setPhotoUrls({});
      setLoading(false);
      return;
    }
    const map: Record<string, string> = {};
    (signed ?? []).forEach((s, i) => {
      const photoId = rowsByPath[i]?.photo_id;
      if (photoId && s.signedUrl) map[photoId] = s.signedUrl;
    });
    setPhotoUrls(map);
    setLoading(false);
  }, [jobId]);

  useEffect(() => {
    load();
    if (!jobId) return;
    const channel = supabase
      .channel(`issues-${jobId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'job_issues', filter: `job_id=eq.${jobId}` }, load)
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, [jobId, load]);

  const resolve = useCallback(async (issueId: string, resolutionNote: string) => {
    const { error } = await supabase
      .from('job_issues')
      .update({
        resolved: true,
        resolved_at: new Date().toISOString(),
        resolution_note: resolutionNote,
      })
      .eq('issue_id', issueId);
    if (error) throw error;
    await append({ job_id: jobId ?? null, type: 'issue_resolved', payload: { issue_id: issueId, resolution_note: resolutionNote } });
  }, [jobId, append]);

  const open = issues.filter((i) => !i.resolved);
  const resolved = issues.filter((i) => i.resolved);

  return { issues, open, resolved, photoUrls, loading, resolve, reload: load };
}
